
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 30 21:23:19 CST 2024
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int include = 16;
  public static final int continueT = 49;
  public static final int signoMultiplicacion = 29;
  public static final int using = 35;
  public static final int SHORT = 5;
  public static final int CHAR = 11;
  public static final int signoMas = 27;
  public static final int signoMenorQue = 22;
  public static final int signoAlmohoadilla = 25;
  public static final int parentesisCierre = 32;
  public static final int T_dato = 3;
  public static final int DOUBLE = 9;
  public static final int igual = 19;
  public static final int INT = 6;
  public static final int llaveCierre = 21;
  public static final int falseT = 53;
  public static final int charT = 40;
  public static final int switchT = 41;
  public static final int doubleT = 39;
  public static final int signoMenos = 28;
  public static final int onceT = 47;
  public static final int EOF = 0;
  public static final int BOOLEAN = 10;
  public static final int RETURN = 15;
  public static final int elseT = 51;
  public static final int error = 1;
  public static final int caseT = 42;
  public static final int signoDosPuntos = 24;
  public static final int signoOr = 34;
  public static final int signoPunto = 33;
  public static final int classT = 37;
  public static final int ERROR = 56;
  public static final int BYTE = 4;
  public static final int trueT = 52;
  public static final int ifT = 50;
  public static final int pragmaT = 46;
  public static final int puntoComa = 17;
  public static final int whileT = 48;
  public static final int returnT = 43;
  public static final int namespace = 36;
  public static final int FLOAT = 8;
  public static final int Identificador = 18;
  public static final int endlT = 45;
  public static final int FALSO = 13;
  public static final int publicT = 38;
  public static final int signoMayorQue = 23;
  public static final int linea = 2;
  public static final int LONG = 7;
  public static final int STRING = 14;
  public static final int VERDADERO = 12;
  public static final int Numero = 55;
  public static final int signoComa = 26;
  public static final int llaveApertura = 20;
  public static final int defaultT = 44;
  public static final int DAY = 54;
  public static final int parentesisApertura = 31;
  public static final int signoSlash = 30;
}

